# Generated by Django 5.2.14 on 2026-06-26 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveHelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_help_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'receive_help_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SendHelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('gpay', 'GPay'), ('phonepe', 'PhonePe'), ('paytm', 'Paytm'), ('upi', 'UPI'), ('bank', 'Bank Transfer')], max_length=10)),
                ('transaction_no', models.CharField(blank=True, max_length=100)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='helpdesk/send/')),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_help_payments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_help_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'send_help_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
