version: '3.8'

services:
  web:
    build: .
    container_name: treeview_django_web
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
