# Generated by Django 5.2.14 on 2026-06-26 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=5)),
                ('joining_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_info', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referrals',
            },
        ),
    ]
