# Generated by Django 5.2.14 on 2026-06-26 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PMFRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_no', models.CharField(blank=True, max_length=100)),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='pmf/proofs/')),
                ('level', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('product_accepted', 'Product Accepted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('dispatched', 'Dispatched')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reply_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmf_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pmf_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
