# Generated by Django 5.2.14 on 2026-06-26 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('aadhaar_file', models.FileField(blank=True, null=True, upload_to='kyc/aadhaar/')),
                ('pan_file', models.FileField(blank=True, null=True, upload_to='kyc/pan/')),
                ('bank_file', models.FileField(blank=True, null=True, upload_to='kyc/bank/')),
                ('photo_file', models.ImageField(blank=True, null=True, upload_to='kyc/photos/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_requests',
            },
        ),
    ]
